env:
  global:
    - CC_TEST_REPORTER_ID=679abebfdfeb5110e342b3f93ecbe433cfa4fdb05ac2216da6b364459be43f9f
language: ruby
rvm:
  # Build on the latest stable of all supported Rubies (https://www.ruby-lang.org/en/downloads/):
  - 2.5.5
  - 2.6.5
  - 2.7.0
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rspec spec --format documentation
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  # https://docs.travis-ci.com/user/uploading-artifacts/
  artifacts:
    paths:
      - Gemfile.lock
